### PR TITLE
init.qcom.rc: Let the kernel handle the i/o scheduler. 

### PR DESCRIPTION
**Pull request by penglezos**
This commit is causing issues with custom kernels applying the desired i/o scheduler.

### CODE REVIEW

**Comment by Zile995** [comment]
Not needed. You can change it with kernel ramdisk init file.

Just add your modifications on property:init.svc.qcom-post-boot=stopped

So if you want to set cfq i/o scheduler add these lines:

on property:init.svc.qcom-post-boot=stopped

    # Make sure the context is correct before init can write to these nodes
     chown system system /sys/block/mmcblk0/queue/scheduler
     chmod 0664 /sys/block/mmcblk0/queue/scheduler
     restorecon /sys/block/mmcblk0/queue/scheduler

     # You can also execute init sh script
     write /sys/block/mmcblk0/queue/scheduler cfq
     write /sys/block/mmcblk1/queue/scheduler cfq

**Comment by penglezos** [comment]
It's actually needed. The kernel should handle this stuff. By having this line it's over writing the configurations that I give inside the kernel. Already know about the ramdisk stuff which its not a proper way. I tested that by myself and the commit I'm pulling request it's actually working fine so I suggest @zeelog to merge.

**Comment by Zile995** [comment]
As you can see here https://github.com/LineageOS/android_vendor_lineage/blob/lineage-16.0/prebuilt/common/etc/init/lineage-iosched.rc

sys.io.scheduler is a proper way of setting an i/o scheduler on lineageos in device tree. But as you said it can be done in kernel.

He can can merge if he wants, I have no problem with that... but it can be "bypassed" on custom kernels.

**Comment by penglezos** [comment]
Indeed but there's no need from the device trees to handle the I/O scheduler since it conflicts with the kernel configurations. Let's keep it clean

**Pull request merged**
