### PR TITLE
Pr2

### PR DESCRIPTION
**Pull request by Astridxx**

### CODE REVIEW

**Review by zeelog — CHANGES_REQUESTED** [review]
mido: prop: Remove unused properties : This doesn't seem right. Some more properties (radio) are still being used.  While I'm almost certain that some properties are useless, I still don't think it's a good idea to just 'remove' them, especially without verifying. So this commit is a no go.

**Review by zeelog — CHANGES_REQUESTED** [review]
mido: Add some properties for miracast : not needed - also, persist.sys.wfd.nohdcp doesn't seem to exist anymore. At least I couldn't find any reference to it.

**Review by zeelog — CHANGES_REQUESTED** [review]
mido: Build libhwc2on1adapter to for display - not needed, built by default.

**Review by zeelog — CHANGES_REQUESTED** [review]
mido: Enable lockscreen charging values  : This is not applicable for Lineage

**Comment by davidtrpchevski** [comment]
Just flashed a build with these changes, CTS also fails with that fingerprint as I said. It's better to leave it untouched. Also is there any reason why the PowerOffAlarm is modified since it doesn't work anyway?

**Comment by davidtrpchevski** [comment]
I will make few comments regarding this pull request. I like it but few things are not okay

1. mido: Switch to caf vndk hals: 

- libz library is missing from vndk-sp-libs.mk even though it is present on CAF [vndk-sp](https://source.codeaurora.org/quic/la/platform/prebuilts/vndk/v28/tree/arm64/arch-arm64-armv8-a/shared/vndk-sp?h=aosp-new/master). We should better stick with the [default](https://source.android.com/devices/architecture/images/vndk_design_android_o.pdf) configuration.

- android.hardware.graphics.mapper@2.0 and android.hardware.graphics.mapper@2.1 should be under android.hardware.graphics.common@1.1 for consistency. 

- android.hidl.base@1.0 is being removed, I am not quite sure about this?

2. mido: Pin modified to PowerOffAlarm app

- As I said previously, it didn't work although it won't hurt having it either.

3. mido: Enable lockscreen charging values

- Doesn't apply to Lineage. it lacks the full patch, most importantly this commit [LockscreenCharging: squashed (2/3)](https://github.com/RevengeOS/android_system_core/commit/9b7128d0f9952a58177f550ec1ecc59bc575acbb).

4. mido: Update build fingerprint to 7.0/NRD90M/9.7.4:

- Fails CTS with developer builts, the best bet is to update it to V10.2.3.0.NCFMIXM although I don't see any reason to do that.

5. mido: prop: Remove unused properties:

- I wouldn't touch these, but I'm fine with the following:

persist.vendor.audio.fluence.voicerec=false \
vendor.audio.offload.passthrough=false \
vendor.audio.parser.ip.buffer.size=262144 \
persist.vendor.camera.display.lmax=1280x720 \
persist.vendor.camera.display.umax=1920x1080 \debug.gralloc.enable_fb_ubwc=1 \
sdm.debug.disable_skip_validate=1 \

**Comment by Astridxx** [comment]
okay I'll try to rewrite

**Pull request closed without merging**
