### PR TITLE
libui: Allow additional gralloc 1.0 buffer usage bits

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by Akianonymus** [comment]
Just say you won't merge 😂

lol

**Comment by zeelog** [comment]
needs further testing, so far I couldn't see the use case for this - i'm awaiting feedback from some testers.

**Comment by Akianonymus** [comment]
this commit should be fixing this log spam

`W MapperHal: buffer descriptor with invalid usage bits 0x2000`

**Comment by Akianonymus** [comment]
I didn't knew before it takes more than 4 days to test this 😮

**Comment by Akianonymus** [comment]
Is this a joke or something ? 🙄

Well nvm

**Comment by Zile995** [comment]
This can be merged now, https://github.com/LineageOS/android_vendor_lineage/commit/9717ee7b80f98777bd8e2758c969541c28698ff5

**Pull request closed without merging**
