### PR TITLE
mido: fix lag in some use-cases

### PR DESCRIPTION
**Pull request by OccupationalTern**
Fixes UI lag while using Live Wallpapers (e.g. Groove) by side-loading Google's Live Wallpaper apk on msm8953 based devices.

Original Change-Id: I92aaa4469f6848e4dfff89f3781f31ed527bae2b

### CODE REVIEW

**Comment by anandsvm** [comment]
Compatible Live Wallpaper works perfect.
Some of the wallpapers lagging not issue of ROM. It's issues of Live Wallpaper itself.

**Comment by OccupationalTern** [comment]
> Compatible Live Wallpaper works perfect.
> Some of the wallpapers lagging not issue of ROM. It's issues of Live Wallpaper itself.

I agree with that @anandsvm . There will still be some live wallpapers that will not work properly(like Geometry wallpaper by Xiaomi that renders the blur in real-time on hardware) but some wallpapers do see some improvements with the UI with this option being disabled. Also, the change is not for wallpapers only but for other UI elements as well. The wallpaper one is an example of what I have noticed with 'Groove' and 'A Drop in the Ocean' wallpapers of Google. On ROMs based on A10, this option being disabled eliminated the UI lag on the homescreen when these wallpapers were applied. I am expecting the same behaviour with A11 ROMs as well since UI handling hasn't changed much. You can test the changes and if it proves to be detrimental to the performance, possibly revert it but I have noticed performance gains from this.

Edit#1: This commit combined with https://github.com/zeelog/android_device_xiaomi_mido/commit/e08228d1151a1822c4edaa49985644c68a7f5709 that Zeelog already merged provided the gains that I mentioned.

**Comment by GiaSen** [comment]
Have you tested if inbuilt screen recorder lags without this prop? I can't test as of now

**Comment by OccupationalTern** [comment]
> Have you tested if inbuilt screen recorder lags without this prop? I can't test as of now

No. I haven't tested Screen Recording with this property being disabled since my results were based on A10 that lacks a native screen recorder. I could have tested it with A11 but I am busy with some personal stuff of mine at the moment. It's effect on the screen recording, however, can't be predicted without testing since the effects of unsignaled buffer latching on SurfaceFlinger aren't well defined and they vary from device to device. It would be great if someone can test it and revert with the results.

**Comment by RahifM** [comment]
i agree, with this flag removed there where noticable improvement on some of google live wallpapers

**Pull request closed without merging**
