### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Astridxx**

### CODE REVIEW

**Review by zeelog — CHANGES_REQUESTED** [review]
Commit: mido: prop: Remove unused properties
these properties are used by mido camera blobs:
persist.camera.gyro.disable=0 \
persist.camera.isp.clock.optmz=0 \
persist.camera.stats.test=5 \
....not sure about the rest, need to check.

**Review by zeelog — CHANGES_REQUESTED** [review]
mido: Build libnl to for miracast - not needed

**Review by zeelog — CHANGES_REQUESTED** [review]
mido: Cleanup vendor_framework_compatibility_matrix - no need to touch this

**Review by zeelog — COMMENTED** [review]
mido: init: Update post boot shell script - from tissot - from which build revision ?

**Comment by Astridxx** [comment]
> mido: init: Update post boot shell script - from tissot - from which build revision ?

Last

**Comment by Astridxx** [comment]
> mido: Build libnl to for miracast - not needed

But need this for libwfdcommonutils.so and libwfdconfigutils.so blobs

**Comment by zeelog** [comment]
> > mido: Build libnl to for miracast - not needed
> 
> But need this for libwfdcommonutils.so and libwfdconfigutils.so blobs

I meant the commit is not needed, as its being built from source anyway

**Pull request closed without merging**
